config/routes.rb
Rails.application.routes.draw do

  resources :contact, only: [:index]
  resources :home, only: [:index]

  root 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contact/index.html.haml
%h1.contact-title
  my contact info

.row
  .large-4.columns
    %ul.pricing-table{data: {'equalizer-watch' => ''}}
      %li.title twitter
      %li.price= link_to '@davidahopp', 'https://twitter.com/davidahopp', target: '_blank'
  .large-4.columns
    %ul.pricing-table{data: {'equalizer-watch' => ''}}
      %li.title github
      %li.price= link_to 'davidahopp', 'https://github.com/davidahopp', target: '_blank'
  .large-4.columns
    %ul.pricing-table{data: {'equalizer-watch' => ''}}
      %li.title linkedIn
      %li.price= link_to 'david hopp', 'https://www.linkedin.com/profile/view?id=170141029', target: '_blank'

app/views/home/_top_bar.html.haml
%nav.top-bar{"data-topbar" => ""}
  %ul.title-area
    %li.name
      %h1
        %a{href: root_path} davidahopp

  = render partial: 'home/top_bar_section', locals: {title: 'contact info', path: contact_index_path}

app/views/home/_top_bar_section.html.haml
%section.top-bar-section
  %ul.left
    %li
      %a{href: path}= title

app/views/home/index.html.haml
.home-page-image

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    = render partial: 'home/top_bar'
    .row{data: {equalizer: ''}}
      .large-12.columns
        = yield

app/views/old_home/index.html.haml
%h1
  Welcome
%p
  While I build the content of this website, please enjoy this picture.

%img{src:'http://placekitten.com/400/400'}


%p
  .twitter
    Want to contact me?
    .handle
      = link_to '@davidahopp', 'https://twitter.com/davidahopp', target: '_blank'